# These are supported funding model platforms for RAYR_Quant

github: [Rayr-06]
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
# lfx_crowdfunding:
# custom:
